# Uncomment and configure once you have set up funding channels.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [myfamilybutler]
# ko_fi: myfamilybutler
# liberapay: myfamilybutler
# open_collective: myfamilybutler
# custom: ["https://www.myfamilybutler.com/support"]
