-- Allow 360dialog channel values for dashboard magic tokens

DO $$
BEGIN
  -- Drop existing autogenerated check constraint if present
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'magic_tokens_channel_check'
      AND conrelid = 'public.magic_tokens'::regclass
  ) THEN
    ALTER TABLE public.magic_tokens
      DROP CONSTRAINT magic_tokens_channel_check;
  END IF;

  -- Recreate check constraint with 360dialog support
  ALTER TABLE public.magic_tokens
    ADD CONSTRAINT magic_tokens_channel_check
    CHECK (channel IN ('whatsapp', 'telegram', '360dialog'));
END $$;

COMMENT ON TABLE public.magic_tokens IS 'Stores short-lived tokens for passwordless dashboard access from WhatsApp/Telegram/360dialog';
